version: '3.8'

services:
  app:
    container_name: home_library_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-4000}:${PORT:-4000}'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      app-network:
        aliases:
          - db
    restart: on-failure

  postgres:
    container_name: home_library_db
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - '${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}'
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      app-network:
        aliases:
          - db
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
